// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHr0vQnnm4phqgVCO2yBDK2aSegiaYeno',
    appId: '1:112732840406:web:ee4dd25314ed4894f10477',
    messagingSenderId: '112732840406',
    projectId: 'my-visitarian-project-287ab',
    authDomain: 'my-visitarian-project-287ab.firebaseapp.com',
    storageBucket: 'my-visitarian-project-287ab.firebasestorage.app',
    measurementId: 'G-WGB2J8Z97V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMdV0mlfHnfmD-0g71seSf11mcZjAjuyY',
    appId: '1:112732840406:android:3acc5ab3385445fcf10477',
    messagingSenderId: '112732840406',
    projectId: 'my-visitarian-project-287ab',
    storageBucket: 'my-visitarian-project-287ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiilD2gx7ay_zBV7nj2R6u_aP-k75IZDY',
    appId: '1:112732840406:ios:e5e8943c879337baf10477',
    messagingSenderId: '112732840406',
    projectId: 'my-visitarian-project-287ab',
    storageBucket: 'my-visitarian-project-287ab.firebasestorage.app',
    iosBundleId: 'com.example.visitarianFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiilD2gx7ay_zBV7nj2R6u_aP-k75IZDY',
    appId: '1:112732840406:ios:e5e8943c879337baf10477',
    messagingSenderId: '112732840406',
    projectId: 'my-visitarian-project-287ab',
    storageBucket: 'my-visitarian-project-287ab.firebasestorage.app',
    iosBundleId: 'com.example.visitarianFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHr0vQnnm4phqgVCO2yBDK2aSegiaYeno',
    appId: '1:112732840406:web:4c7eec4af97726f2f10477',
    messagingSenderId: '112732840406',
    projectId: 'my-visitarian-project-287ab',
    authDomain: 'my-visitarian-project-287ab.firebaseapp.com',
    storageBucket: 'my-visitarian-project-287ab.firebasestorage.app',
    measurementId: 'G-G4S7446Y7R',
  );
}
